#############################################################################
# Makefile for building: KeCameraPluginProject
# Generated by qmake (3.0) (Qt 5.1.1) on: ?? ??? 4 15:24:51 2013
# Project:  KeCameraPluginProject.pro
# Template: subdirs
# Command: D:\Qt\5.1.1\msvc2010\bin\qmake.exe -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile KeCameraPluginProject.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = D:\Qt\5.1.1\msvc2010\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-KeCameraPlugin \
		sub-CameraClient \
		sub-KENetSDK \
		sub-TestCaseSDKLib \
		sub-NetSDKDemo


sub-KeCameraPlugin-qmake_all:  FORCE
	@if not exist KeCameraPlugin\ mkdir KeCameraPlugin\ & if not exist KeCameraPlugin\ exit 1
	cd KeCameraPlugin\ && $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KeCameraPlugin\KeCameraPlugin.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KeCameraPlugin\ && $(MAKE) -f Makefile qmake_all
sub-KeCameraPlugin: FORCE
	@if not exist KeCameraPlugin\ mkdir KeCameraPlugin\ & if not exist KeCameraPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KeCameraPlugin\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KeCameraPlugin\KeCameraPlugin.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-KeCameraPlugin-make_first: FORCE
	@if not exist KeCameraPlugin\ mkdir KeCameraPlugin\ & if not exist KeCameraPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KeCameraPlugin\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KeCameraPlugin\KeCameraPlugin.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-KeCameraPlugin-all: FORCE
	@if not exist KeCameraPlugin\ mkdir KeCameraPlugin\ & if not exist KeCameraPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KeCameraPlugin\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KeCameraPlugin\KeCameraPlugin.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-KeCameraPlugin-clean: FORCE
	@if not exist KeCameraPlugin\ mkdir KeCameraPlugin\ & if not exist KeCameraPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KeCameraPlugin\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KeCameraPlugin\KeCameraPlugin.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-KeCameraPlugin-distclean: FORCE
	@if not exist KeCameraPlugin\ mkdir KeCameraPlugin\ & if not exist KeCameraPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KeCameraPlugin\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KeCameraPlugin\KeCameraPlugin.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-KeCameraPlugin-install_subtargets: FORCE
	@if not exist KeCameraPlugin\ mkdir KeCameraPlugin\ & if not exist KeCameraPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KeCameraPlugin\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KeCameraPlugin\KeCameraPlugin.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-KeCameraPlugin-uninstall_subtargets: FORCE
	@if not exist KeCameraPlugin\ mkdir KeCameraPlugin\ & if not exist KeCameraPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KeCameraPlugin\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KeCameraPlugin\KeCameraPlugin.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-CameraClient-qmake_all:  FORCE
	@if not exist CameraClient\ mkdir CameraClient\ & if not exist CameraClient\ exit 1
	cd CameraClient\ && $(QMAKE) E:\workspace\qt\KeCameraPluginProject\CameraClient\CameraClient.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CameraClient\ && $(MAKE) -f Makefile qmake_all
sub-CameraClient: FORCE
	@if not exist CameraClient\ mkdir CameraClient\ & if not exist CameraClient\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CameraClient\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\CameraClient\CameraClient.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-CameraClient-make_first: FORCE
	@if not exist CameraClient\ mkdir CameraClient\ & if not exist CameraClient\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CameraClient\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\CameraClient\CameraClient.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-CameraClient-all: FORCE
	@if not exist CameraClient\ mkdir CameraClient\ & if not exist CameraClient\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CameraClient\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\CameraClient\CameraClient.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-CameraClient-clean: FORCE
	@if not exist CameraClient\ mkdir CameraClient\ & if not exist CameraClient\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CameraClient\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\CameraClient\CameraClient.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-CameraClient-distclean: FORCE
	@if not exist CameraClient\ mkdir CameraClient\ & if not exist CameraClient\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CameraClient\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\CameraClient\CameraClient.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-CameraClient-install_subtargets: FORCE
	@if not exist CameraClient\ mkdir CameraClient\ & if not exist CameraClient\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CameraClient\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\CameraClient\CameraClient.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-CameraClient-uninstall_subtargets: FORCE
	@if not exist CameraClient\ mkdir CameraClient\ & if not exist CameraClient\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CameraClient\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\CameraClient\CameraClient.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-KENetSDK-qmake_all:  FORCE
	@if not exist KENetSDK\ mkdir KENetSDK\ & if not exist KENetSDK\ exit 1
	cd KENetSDK\ && $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KENetSDK\KENetSDK.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KENetSDK\ && $(MAKE) -f Makefile qmake_all
sub-KENetSDK: FORCE
	@if not exist KENetSDK\ mkdir KENetSDK\ & if not exist KENetSDK\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KENetSDK\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KENetSDK\KENetSDK.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-KENetSDK-make_first: FORCE
	@if not exist KENetSDK\ mkdir KENetSDK\ & if not exist KENetSDK\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KENetSDK\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KENetSDK\KENetSDK.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-KENetSDK-all: FORCE
	@if not exist KENetSDK\ mkdir KENetSDK\ & if not exist KENetSDK\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KENetSDK\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KENetSDK\KENetSDK.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-KENetSDK-clean: FORCE
	@if not exist KENetSDK\ mkdir KENetSDK\ & if not exist KENetSDK\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KENetSDK\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KENetSDK\KENetSDK.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-KENetSDK-distclean: FORCE
	@if not exist KENetSDK\ mkdir KENetSDK\ & if not exist KENetSDK\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KENetSDK\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KENetSDK\KENetSDK.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-KENetSDK-install_subtargets: FORCE
	@if not exist KENetSDK\ mkdir KENetSDK\ & if not exist KENetSDK\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KENetSDK\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KENetSDK\KENetSDK.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-KENetSDK-uninstall_subtargets: FORCE
	@if not exist KENetSDK\ mkdir KENetSDK\ & if not exist KENetSDK\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KENetSDK\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KENetSDK\KENetSDK.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-TestCaseSDKLib-qmake_all:  FORCE
	@if not exist TestCaseSDKLib\ mkdir TestCaseSDKLib\ & if not exist TestCaseSDKLib\ exit 1
	cd TestCaseSDKLib\ && $(QMAKE) E:\workspace\qt\KeCameraPluginProject\TestCaseSDKLib\TestCaseSDKLib.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TestCaseSDKLib\ && $(MAKE) -f Makefile qmake_all
sub-TestCaseSDKLib: FORCE
	@if not exist TestCaseSDKLib\ mkdir TestCaseSDKLib\ & if not exist TestCaseSDKLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TestCaseSDKLib\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\TestCaseSDKLib\TestCaseSDKLib.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-TestCaseSDKLib-make_first: FORCE
	@if not exist TestCaseSDKLib\ mkdir TestCaseSDKLib\ & if not exist TestCaseSDKLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TestCaseSDKLib\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\TestCaseSDKLib\TestCaseSDKLib.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-TestCaseSDKLib-all: FORCE
	@if not exist TestCaseSDKLib\ mkdir TestCaseSDKLib\ & if not exist TestCaseSDKLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TestCaseSDKLib\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\TestCaseSDKLib\TestCaseSDKLib.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-TestCaseSDKLib-clean: FORCE
	@if not exist TestCaseSDKLib\ mkdir TestCaseSDKLib\ & if not exist TestCaseSDKLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TestCaseSDKLib\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\TestCaseSDKLib\TestCaseSDKLib.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-TestCaseSDKLib-distclean: FORCE
	@if not exist TestCaseSDKLib\ mkdir TestCaseSDKLib\ & if not exist TestCaseSDKLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TestCaseSDKLib\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\TestCaseSDKLib\TestCaseSDKLib.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-TestCaseSDKLib-install_subtargets: FORCE
	@if not exist TestCaseSDKLib\ mkdir TestCaseSDKLib\ & if not exist TestCaseSDKLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TestCaseSDKLib\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\TestCaseSDKLib\TestCaseSDKLib.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-TestCaseSDKLib-uninstall_subtargets: FORCE
	@if not exist TestCaseSDKLib\ mkdir TestCaseSDKLib\ & if not exist TestCaseSDKLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TestCaseSDKLib\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\TestCaseSDKLib\TestCaseSDKLib.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-NetSDKDemo-qmake_all:  FORCE
	@if not exist NetSDKDemo\ mkdir NetSDKDemo\ & if not exist NetSDKDemo\ exit 1
	cd NetSDKDemo\ && $(QMAKE) E:\workspace\qt\KeCameraPluginProject\NetSDKDemo\NetSDKDemo.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetSDKDemo\ && $(MAKE) -f Makefile qmake_all
sub-NetSDKDemo: FORCE
	@if not exist NetSDKDemo\ mkdir NetSDKDemo\ & if not exist NetSDKDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetSDKDemo\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\NetSDKDemo\NetSDKDemo.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-NetSDKDemo-make_first: FORCE
	@if not exist NetSDKDemo\ mkdir NetSDKDemo\ & if not exist NetSDKDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetSDKDemo\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\NetSDKDemo\NetSDKDemo.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-NetSDKDemo-all: FORCE
	@if not exist NetSDKDemo\ mkdir NetSDKDemo\ & if not exist NetSDKDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetSDKDemo\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\NetSDKDemo\NetSDKDemo.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-NetSDKDemo-clean: FORCE
	@if not exist NetSDKDemo\ mkdir NetSDKDemo\ & if not exist NetSDKDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetSDKDemo\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\NetSDKDemo\NetSDKDemo.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-NetSDKDemo-distclean: FORCE
	@if not exist NetSDKDemo\ mkdir NetSDKDemo\ & if not exist NetSDKDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetSDKDemo\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\NetSDKDemo\NetSDKDemo.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-NetSDKDemo-install_subtargets: FORCE
	@if not exist NetSDKDemo\ mkdir NetSDKDemo\ & if not exist NetSDKDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetSDKDemo\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\NetSDKDemo\NetSDKDemo.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-NetSDKDemo-uninstall_subtargets: FORCE
	@if not exist NetSDKDemo\ mkdir NetSDKDemo\ & if not exist NetSDKDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetSDKDemo\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\NetSDKDemo\NetSDKDemo.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: KeCameraPluginProject.pro D:\Qt\5.1.1\msvc2010\mkspecs\win32-msvc2010\qmake.conf D:\Qt\5.1.1\msvc2010\mkspecs\features\spec_pre.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\common\shell-win32.conf \
		D:\Qt\5.1.1\msvc2010\mkspecs\qconfig.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_axbase.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_axcontainer.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_axserver.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_clucene.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_concurrent.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_core.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_declarative.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_designer.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_designercomponents.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_gui.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_help.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_multimedia.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_network.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_opengl.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_openglextensions.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_platformsupport.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_printsupport.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_qml.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_qmldevtools.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_qmltest.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_quick.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_quickparticles.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_script.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_scripttools.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_sensors.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_serialport.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_sql.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_svg.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_testlib.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_uitools.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_v8.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_webkit.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_webkitwidgets.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_widgets.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_xml.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_xmlpatterns.pri \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\qt_functions.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\qt_config.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\win32-msvc2010\qmake.conf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\spec_post.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\exclusive_builds.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\default_pre.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\win32\default_pre.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\resolve_config.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\default_post.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\qml_debug.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\declarative_debug.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\win32\rtti.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\warn_on.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\win32\windows.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\testcase_targets.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\exceptions.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\yacc.prf \
		D:\Qt\5.1.1\msvc2010\mkspecs\features\lex.prf \
		KeCameraPluginProject.pro
	$(QMAKE) -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile KeCameraPluginProject.pro
D:\Qt\5.1.1\msvc2010\mkspecs\features\spec_pre.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\common\shell-win32.conf:
D:\Qt\5.1.1\msvc2010\mkspecs\qconfig.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_axbase.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_axcontainer.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_axserver.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_clucene.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_concurrent.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_core.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_declarative.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_designer.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_designercomponents.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_gui.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_help.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_multimedia.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_network.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_opengl.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_openglextensions.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_platformsupport.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_printsupport.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_qml.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_qmldevtools.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_qmltest.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_quick.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_quickparticles.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_script.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_scripttools.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_sensors.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_serialport.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_sql.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_svg.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_testlib.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_uitools.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_v8.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_webkit.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_webkitwidgets.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_widgets.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_xml.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\Qt\5.1.1\msvc2010\mkspecs\features\qt_functions.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\qt_config.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\win32-msvc2010\qmake.conf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\spec_post.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\exclusive_builds.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\default_pre.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\win32\default_pre.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\resolve_config.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\default_post.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\qml_debug.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\declarative_debug.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\win32\rtti.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\warn_on.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\win32\windows.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\testcase_targets.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\exceptions.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\yacc.prf:
D:\Qt\5.1.1\msvc2010\mkspecs\features\lex.prf:
KeCameraPluginProject.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile KeCameraPluginProject.pro

qmake_all: sub-KeCameraPlugin-qmake_all sub-CameraClient-qmake_all sub-KENetSDK-qmake_all sub-TestCaseSDKLib-qmake_all sub-NetSDKDemo-qmake_all FORCE

make_first: sub-KeCameraPlugin-make_first sub-CameraClient-make_first sub-KENetSDK-make_first sub-TestCaseSDKLib-make_first sub-NetSDKDemo-make_first FORCE
all: sub-KeCameraPlugin-all sub-CameraClient-all sub-KENetSDK-all sub-TestCaseSDKLib-all sub-NetSDKDemo-all FORCE
clean: sub-KeCameraPlugin-clean sub-CameraClient-clean sub-KENetSDK-clean sub-TestCaseSDKLib-clean sub-NetSDKDemo-clean FORCE
distclean: sub-KeCameraPlugin-distclean sub-CameraClient-distclean sub-KENetSDK-distclean sub-TestCaseSDKLib-distclean sub-NetSDKDemo-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-KeCameraPlugin-install_subtargets sub-CameraClient-install_subtargets sub-KENetSDK-install_subtargets sub-TestCaseSDKLib-install_subtargets sub-NetSDKDemo-install_subtargets FORCE
uninstall_subtargets: sub-KeCameraPlugin-uninstall_subtargets sub-CameraClient-uninstall_subtargets sub-KENetSDK-uninstall_subtargets sub-TestCaseSDKLib-uninstall_subtargets sub-NetSDKDemo-uninstall_subtargets FORCE

sub-KeCameraPlugin-sub_Debug:
	@if not exist KeCameraPlugin\ mkdir KeCameraPlugin\ & if not exist KeCameraPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KeCameraPlugin\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KeCameraPlugin\KeCameraPlugin.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-CameraClient-sub_Debug:
	@if not exist CameraClient\ mkdir CameraClient\ & if not exist CameraClient\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CameraClient\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\CameraClient\CameraClient.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-KENetSDK-sub_Debug:
	@if not exist KENetSDK\ mkdir KENetSDK\ & if not exist KENetSDK\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KENetSDK\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KENetSDK\KENetSDK.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-TestCaseSDKLib-sub_Debug:
	@if not exist TestCaseSDKLib\ mkdir TestCaseSDKLib\ & if not exist TestCaseSDKLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TestCaseSDKLib\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\TestCaseSDKLib\TestCaseSDKLib.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-NetSDKDemo-sub_Debug:
	@if not exist NetSDKDemo\ mkdir NetSDKDemo\ & if not exist NetSDKDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetSDKDemo\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\NetSDKDemo\NetSDKDemo.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-KeCameraPlugin-sub_Debug sub-CameraClient-sub_Debug sub-KENetSDK-sub_Debug sub-TestCaseSDKLib-sub_Debug sub-NetSDKDemo-sub_Debug

sub-KeCameraPlugin-sub_Release:
	@if not exist KeCameraPlugin\ mkdir KeCameraPlugin\ & if not exist KeCameraPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KeCameraPlugin\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KeCameraPlugin\KeCameraPlugin.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile release
sub-CameraClient-sub_Release:
	@if not exist CameraClient\ mkdir CameraClient\ & if not exist CameraClient\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CameraClient\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\CameraClient\CameraClient.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile release
sub-KENetSDK-sub_Release:
	@if not exist KENetSDK\ mkdir KENetSDK\ & if not exist KENetSDK\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KENetSDK\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KENetSDK\KENetSDK.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile release
sub-TestCaseSDKLib-sub_Release:
	@if not exist TestCaseSDKLib\ mkdir TestCaseSDKLib\ & if not exist TestCaseSDKLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TestCaseSDKLib\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\TestCaseSDKLib\TestCaseSDKLib.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile release
sub-NetSDKDemo-sub_Release:
	@if not exist NetSDKDemo\ mkdir NetSDKDemo\ & if not exist NetSDKDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetSDKDemo\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\NetSDKDemo\NetSDKDemo.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile release
release: sub-KeCameraPlugin-sub_Release sub-CameraClient-sub_Release sub-KENetSDK-sub_Release sub-TestCaseSDKLib-sub_Release sub-NetSDKDemo-sub_Release

sub-KeCameraPlugin-check:
	@if not exist KeCameraPlugin\ mkdir KeCameraPlugin\ & if not exist KeCameraPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KeCameraPlugin\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KeCameraPlugin\KeCameraPlugin.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-CameraClient-check:
	@if not exist CameraClient\ mkdir CameraClient\ & if not exist CameraClient\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd CameraClient\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\CameraClient\CameraClient.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-KENetSDK-check:
	@if not exist KENetSDK\ mkdir KENetSDK\ & if not exist KENetSDK\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd KENetSDK\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\KENetSDK\KENetSDK.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-TestCaseSDKLib-check:
	@if not exist TestCaseSDKLib\ mkdir TestCaseSDKLib\ & if not exist TestCaseSDKLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd TestCaseSDKLib\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\TestCaseSDKLib\TestCaseSDKLib.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-NetSDKDemo-check:
	@if not exist NetSDKDemo\ mkdir NetSDKDemo\ & if not exist NetSDKDemo\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd NetSDKDemo\ && ( if not exist Makefile $(QMAKE) E:\workspace\qt\KeCameraPluginProject\NetSDKDemo\NetSDKDemo.pro -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-KeCameraPlugin-check sub-CameraClient-check sub-KENetSDK-check sub-TestCaseSDKLib-check sub-NetSDKDemo-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

